/**
 * Local JSON store — writes parsed Actions to disk instead of Supabase.
 * Import to Supabase later via SQL or admin panel.
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "fs";
import { join } from "path";
import type { ParsedActionData, SyncStats } from "./types";

const OUTPUT_DIR = join(import.meta.dirname, "../../output");

interface StoredAction extends ParsedActionData {
  /** Unique key for dedup (proof_metadata_link) */
  _key: string;
  _synced_at: string;
}

function ensureDir() {
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }
}

function loadExisting(): StoredAction[] {
  const path = join(OUTPUT_DIR, "actions.json");
  if (!existsSync(path)) return [];
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return [];
  }
}

export function runLocalSync(
  records: { raw: any; parse: (raw: any) => ParsedActionData }[],
  dryRun: boolean
): SyncStats {
  ensureDir();

  const existing = loadExisting();
  const existingKeys = new Set(existing.map((a) => a._key));

  const stats: SyncStats = { successCount: 0, skipCount: 0, errorCount: 0 };
  const newActions: StoredAction[] = [];

  for (const { raw, parse } of records) {
    try {
      const action = parse(raw);

      if (existingKeys.has(action.proof_metadata_link)) {
        console.log(`  ⏭️  Skipping "${action.title}" — already stored`);
        stats.skipCount++;
        continue;
      }

      if (dryRun) {
        console.log(
          `  [DRY RUN] Would store: "${action.title}" | ${action.sdg_ids.length} SDGs | actor: ${action.actor_name || "—"} | geo: ${action.geography ? "yes" : "no"}`
        );
        stats.successCount++;
        continue;
      }

      newActions.push({
        ...action,
        _key: action.proof_metadata_link,
        _synced_at: new Date().toISOString(),
      });
      existingKeys.add(action.proof_metadata_link);
      console.log(
        `  ✅ Stored: "${action.title}" | ${action.sdg_ids.length} SDGs | actor: ${action.actor_name || "—"}`
      );
      stats.successCount++;
    } catch (error) {
      console.error(`  ✗ Error processing record:`, error);
      stats.errorCount++;
    }
  }

  if (!dryRun && newActions.length > 0) {
    const all = [...existing, ...newActions];
    writeFileSync(
      join(OUTPUT_DIR, "actions.json"),
      JSON.stringify(all, null, 2)
    );
    console.log(`\n  📁 Wrote ${all.length} total actions to output/actions.json`);

    // Also write Supabase-ready SQL
    writeSQLImport(all);

    // Also write summary stats
    writeSummary(all);
  }

  return stats;
}

function writeSQLImport(actions: StoredAction[]) {
  const lines: string[] = [
    "-- Hedera Guardian Actions — Supabase import",
    "-- Generated by hedera-hello-future integrations connector",
    `-- ${actions.length} actions, ${new Date().toISOString()}`,
    "",
    "-- Step 1: Create protocol",
    `INSERT INTO actions_protocols (name, color, website)`,
    `VALUES ('Hedera Guardian', '#8259EF', 'https://guardian.hedera.com')`,
    `ON CONFLICT (name) DO NOTHING;`,
    "",
    "-- Step 2: Create actors",
  ];

  const actors = [...new Set(actions.map((a) => a.actor_name).filter(Boolean))];
  for (const actor of actors) {
    lines.push(
      `INSERT INTO actions_actors (name) VALUES ('${actor}') ON CONFLICT DO NOTHING;`
    );
  }

  lines.push("", "-- Step 3: Insert actions");
  for (const action of actions) {
    const title = action.title.replace(/'/g, "''");
    const desc = (action.description || "").replace(/'/g, "''");
    const geo = action.geography ? `ST_GeomFromText('${action.geography}', 4326)` : "NULL";
    const startDate = action.action_start_date ? `'${action.action_start_date}'` : "NULL";

    lines.push(`
DO $$
DECLARE action_id UUID;
DECLARE actor_id UUID;
DECLARE protocol_id UUID;
BEGIN
  SELECT id INTO protocol_id FROM actions_protocols WHERE name = 'Hedera Guardian';

  INSERT INTO actions (title, description, geography, action_start_date, status)
  VALUES ('${title}', '${desc}', ${geo}, ${startDate}, 'DRAFT')
  RETURNING id INTO action_id;

  ${action.actor_name ? `SELECT id INTO actor_id FROM actions_actors WHERE name = '${action.actor_name}';
  INSERT INTO actions_actors_map (action_id, actor_id) VALUES (action_id, actor_id);` : ""}

  INSERT INTO actions_proofs (action_id, protocol_id, proof_link, proof_metadata_link, proof_explorer_link)
  VALUES (action_id, protocol_id, '${action.proof_link || ""}', '${action.proof_metadata_link}', '${action.explorer_link}');

  ${action.sdg_ids.map((id) => `INSERT INTO actions_sdgs_map (action_id, sdg_id) VALUES (action_id, ${id});`).join("\n  ")}
END $$;`);
  }

  writeFileSync(join(OUTPUT_DIR, "import.sql"), lines.join("\n"));
  console.log(`  📁 Wrote SQL import script to output/import.sql`);
}

function writeSummary(actions: StoredAction[]) {
  const byActor: Record<string, number> = {};
  let withGeo = 0;
  let withoutGeo = 0;

  for (const a of actions) {
    const actor = a.actor_name || "Unknown";
    byActor[actor] = (byActor[actor] || 0) + 1;
    if (a.geography) withGeo++;
    else withoutGeo++;
  }

  const summary = {
    total: actions.length,
    with_geography: withGeo,
    without_geography: withoutGeo,
    by_actor: byActor,
    generated_at: new Date().toISOString(),
  };

  writeFileSync(
    join(OUTPUT_DIR, "summary.json"),
    JSON.stringify(summary, null, 2)
  );
  console.log(`  📁 Wrote summary to output/summary.json`);
}
