#!/usr/bin/env npx tsx
/**
 * Create a Hedera testnet account via the faucet API.
 * Generates an ED25519 key pair, requests testnet HBAR, writes creds to .env
 */

import { PrivateKey } from "@hashgraph/sdk";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { join } from "path";

const FAUCET_URL = "https://faucet.hedera.com/api/account";
const ENV_PATH = join(import.meta.dirname, "../.env");

async function main() {
  console.log("Generating ED25519 key pair...");
  const privateKey = PrivateKey.generateED25519();
  const publicKey = privateKey.publicKey;

  console.log(`Public key:  ${publicKey.toStringDer()}`);
  console.log(`Private key: ${privateKey.toStringDer().slice(0, 20)}...`);

  console.log("\nRequesting testnet account from faucet...");
  const res = await fetch(FAUCET_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      publicKey: publicKey.toStringDer(),
      network: "testnet",
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Faucet request failed (${res.status}): ${text}`);
  }

  const data = await res.json();
  const accountId = data.account || data.accountId;

  if (!accountId) {
    console.log("Faucet response:", JSON.stringify(data, null, 2));
    throw new Error("No account ID in faucet response");
  }

  console.log(`\nTestnet account created: ${accountId}`);
  console.log(`View on HashScan: https://hashscan.io/testnet/account/${accountId}`);

  // Write to .env
  const envLines = [
    "",
    "# Hedera Testnet (auto-generated by setup-testnet.ts)",
    `HEDERA_OPERATOR_ID=${accountId}`,
    `HEDERA_OPERATOR_KEY=${privateKey.toStringDer()}`,
    `HEDERA_NETWORK=testnet`,
  ];

  let existing = "";
  if (existsSync(ENV_PATH)) {
    existing = readFileSync(ENV_PATH, "utf-8");
    // Remove old Hedera vars if present
    existing = existing
      .split("\n")
      .filter((l) => !l.startsWith("HEDERA_OPERATOR_ID=") && !l.startsWith("HEDERA_OPERATOR_KEY=") && !l.startsWith("HEDERA_NETWORK="))
      .join("\n");
  }

  writeFileSync(ENV_PATH, existing.trimEnd() + "\n" + envLines.join("\n") + "\n");
  console.log(`\nCredentials written to integrations/.env`);
  console.log("Run: npm run publish:hedera");
}

main().catch((e) => {
  console.error("Setup failed:", e.message);
  process.exit(1);
});
