/**
 * Hedera Guardian intelligence source
 *
 * Loads pre-built VerifiableProvenance objects from static JSON.
 * These are generated by integrations/src/build-static.ts from Mirror Node data.
 */

import type { VerifiableProvenance } from "../types";

let cachedProvenances: VerifiableProvenance[] | null = null;

/**
 * Fetch Hedera Guardian provenance objects from static JSON
 */
export async function fetchHederaProvenances(): Promise<VerifiableProvenance[]> {
  if (cachedProvenances) return cachedProvenances;

  try {
    const res = await fetch("/data/hedera-provenance.json");
    if (!res.ok) {
      console.warn(`Failed to load Hedera provenance data: ${res.status}`);
      return [];
    }
    cachedProvenances = await res.json();
    return cachedProvenances!;
  } catch (err) {
    console.warn("Failed to load Hedera provenance data:", err);
    return [];
  }
}

export function getHederaSourceMeta(
  endpoint: string,
  queryParams: Record<string, string> = {}
) {
  return {
    protocol: "hedera" as const,
    endpoint,
    queryParams,
    fetchedAt: new Date().toISOString(),
  };
}
